"""PDF Shop Drawing Export — generates print-ready PDF with title block."""
from pathlib import Path
from datetime import datetime


def export_pdf_shop_drawing(dxf_path: Path, pdf_path: Path, furniture_type: str = "Furniture",
                            dimensions: dict = None, scale_note: str = "Metric (cm)"):
    """
    Generate a print-ready PDF shop drawing from the DXF.
    Uses matplotlib for rendering since it's already a dependency.
    """
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from matplotlib.patches import Rectangle, Circle, FancyBboxPatch
    import matplotlib.lines as mlines

    dims = dimensions or {}

    fig, ax = plt.subplots(figsize=(11.7, 8.3))  # A3
    ax.set_xlim(0, 420)
    ax.set_ylim(0, 297)
    ax.set_aspect('equal')
    ax.axis('off')

    # Border
    ax.add_patch(Rectangle((5, 5), 410, 287, fill=False, edgecolor='black', linewidth=1.5))

    # Title block
    tb_x, tb_y = 420 - 180 - 10, 10
    tb_w, tb_h = 180, 50
    ax.add_patch(Rectangle((tb_x, tb_y), tb_w, tb_h, fill=False, edgecolor='black'))
    ax.plot([tb_x, tb_x + tb_w], [tb_y + tb_h - 15, tb_y + tb_h - 15], color='black', linewidth=0.5)
    ax.plot([tb_x, tb_x + tb_w], [tb_y + tb_h - 30, tb_y + tb_h - 30], color='black', linewidth=0.5)

    now = datetime.now().strftime('%Y-%m-%d')
    ax.text(tb_x + 5, tb_y + 2, f'DRAWING: {furniture_type}', fontsize=8, fontfamily='monospace')
    ax.text(tb_x + 5, tb_y + 17, f'SCALE: {scale_note}    DATE: {now}', fontsize=8, fontfamily='monospace')
    ax.text(tb_x + 5, tb_y + 32, 'DESIGNER: AI CAD Drafter (10/10)', fontsize=8, fontfamily='monospace')

    # Title
    ax.text(210, 285, f'SHOP DRAWING - {furniture_type.upper()}', fontsize=14,
            fontweight='bold', ha='center', fontfamily='monospace')

    # Dimensions info
    y = 260
    for k, v in dims.items():
        if v and k != 'unit':
            ax.text(20, y, f'{k.replace("_", " ").title()}: {v} {dims.get("unit", "cm")}',
                    fontsize=9, fontfamily='monospace')
            y -= 10

    # Draw simple representation
    dia = dims.get('diameter', dims.get('width', 80))
    height = dims.get('height', 70)

    # Top view (circle)
    cx, cy = 100, 180
    r = min(dia / 2 * 0.5, 60)
    if r > 5:
        ax.add_patch(Circle((cx, cy), r, fill=False, edgecolor='black', linewidth=1.5))
        ax.plot([cx - r - 10, cx + r + 10], [cy, cy], color='blue', linewidth=0.5, linestyle='--')
        ax.plot([cx, cx], [cy - r - 10, cy + r + 10], color='blue', linewidth=0.5, linestyle='--')
        ax.annotate(f'O{dia}cm', (cx, cy - r - 15), fontsize=8, ha='center', fontfamily='monospace')
        ax.text(cx - 15, cy + r + 8, 'TOP VIEW', fontsize=8, fontfamily='monospace', ha='center')

    # Front view (rectangle)
    fx, fy = 280, 180
    w = min(dia * 0.5, 80)
    h = min(height * 0.5, 80)
    ax.add_patch(Rectangle((fx - w / 2, fy - h / 2), w, h, fill=False, edgecolor='black', linewidth=1.5))
    ax.annotate(f'H={height}cm', (fx + w / 2 + 8, fy), fontsize=8, fontfamily='monospace')
    ax.text(fx, fy + h / 2 + 10, 'FRONT VIEW', fontsize=8, fontfamily='monospace', ha='center')

    # Footer
    ax.text(210, 8, f'Generated by CAD Scaler Digitizer v2.0 — {now}',
            fontsize=6, ha='center', fontfamily='monospace', color='gray')

    plt.tight_layout(pad=0)
    fig.savefig(str(pdf_path), dpi=150, facecolor='white')
    plt.close(fig)
    return pdf_path
